OBJ +=\
	$(dir)/rune.o\
	$(dir)/runestrcat.o\
	$(dir)/runestrchr.o\
	$(dir)/runestrcmp.o\
	$(dir)/runestrcpy.o\
	$(dir)/runestrdup.o\
	$(dir)/runestrlen.o\
	$(dir)/runestrecpy.o\
	$(dir)/runestrncat.o\
	$(dir)/runestrncmp.o\
	$(dir)/runestrncpy.o\
	$(dir)/runestrrchr.o\
	$(dir)/runestrstr.o\
	$(dir)/runetype.o\
	$(dir)/utfecpy.o\
	$(dir)/utflen.o\
	$(dir)/utfnlen.o\
	$(dir)/utfrrune.o\
	$(dir)/utfrune.o\
	$(dir)/utfutf.o\

$(dir)/%.o: utf.h
$(dir)/%.o: CFLAGS += -Wno-missing-braces -Wno-parentheses -Wno-switch -Wno-sign-compare -fPIC -O2 -g